services:
  namorix-weave:
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        - namorix=../../namorix
    image: namorix/addon-weave:prod
    container_name: namorix-addon-weave
    ports:
      - "5100:5100"
    labels:
      - "namorix-addon=true"
      - "namorix-addon-id=namorix-weave"
      - "namorix-addon-name=Namorix Weave"
      - "namorix-addon-author=IzeroCs"
      - "namorix-addon-description=Connect and monitor smart home devices across your Thread mesh"
