// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Namorix.Weave.Persistence;

#nullable disable

namespace Namorix.Weave.Migrations
{
    [DbContext(typeof(WeaveDbContext))]
    [Migration("20260814022928_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Namorix.Weave.Models.BrThreadDataset", b =>
                {
                    b.Property<int>("NetworkId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ChannelMask")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ExtendedPanId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("MeshLocalPrefix")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("NetworkKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkName")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("PanId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Pskc")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SecurityPolicy")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("NetworkId");

                    b.ToTable("BrThreadDataset");
                });

            modelBuilder.Entity("Namorix.Weave.Models.Network", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Eui64")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Eui64")
                        .IsUnique()
                        .HasFilter("\"Eui64\" IS NOT NULL");

                    b.ToTable("Networks");
                });

            modelBuilder.Entity("Namorix.Weave.Models.BrThreadDataset", b =>
                {
                    b.HasOne("Namorix.Weave.Models.Network", "Network")
                        .WithOne("ThreadDataset")
                        .HasForeignKey("Namorix.Weave.Models.BrThreadDataset", "NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");
                });

            modelBuilder.Entity("Namorix.Weave.Models.Network", b =>
                {
                    b.Navigation("ThreadDataset");
                });
#pragma warning restore 612, 618
        }
    }
}
